=== austinejei/xmltoussd/xmltoussd.app/xml2ussd.dtd
<!ELEMENT ussd (screen+)>
<!ELEMENT screen (text|form|menu|action+)>
<!ATTLIST screen id ID #REQUIRED>

<!ELEMENT text (#PCDATA)>
<!ATTLIST text bindfrom CDATA #IMPLIED>
<!ATTLIST text bindaction CDATA #IMPLIED>


<!ELEMENT form (title,input+,list+)>
<!ATTLIST form bindto CDATA #REQUIRED>
<!ATTLIST form onsubmit CDATA #REQUIRED>

<!ELEMENT input (#PCDATA)>
<!ATTLIST input type (text|number|money|list) #REQUIRED>
<!ATTLIST input id ID #REQUIRED>
<!ATTLIST input required (true|false) #REQUIRED>
<!ATTLIST input display CDATA #REQUIRED>
<!ATTLIST input maxlength CDATA #IMPLIED>

<!ELEMENT list (choice+)>
<!ATTLIST list id ID #REQUIRED>
<!ELEMENT choice (#PCDATA)>
<!ATTLIST choice value CDATA #REQUIRED>
<!ATTLIST choice selector CDATA #IMPLIED> <!--if not specified, will default to 1,2,3-->

<!ELEMENT menu (title,option+)>
<!ATTLIST menu bindfrom CDATA #IMPLIED>
<!ATTLIST menu bindaction CDATA #IMPLIED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option value CDATA #REQUIRED>
<!ATTLIST option onselect CDATA #REQUIRED>

<!ELEMENT action (http)>
<!ATTLIST action id ID #REQUIRED>
<!ATTLIST action bindto CDATA #IMPLIED>
<!ATTLIST action cycle (Once|Always) #IMPLIED>
<!ELEMENT http (header,body,response)>
<!ATTLIST http url CDATA #REQUIRED>
<!ATTLIST http method (Post|Put|Get|Delete|Patch) #REQUIRED>

<!ELEMENT header (add+)>
<!ELEMENT add (#PCDATA)>
<!ATTLIST add key CDATA #REQUIRED>
<!ATTLIST add value CDATA #REQUIRED>

<!ELEMENT body (#PCDATA)>
<!ATTLIST body bindfrom CDATA #IMPLIED>

<!ELEMENT response (code+)>
<!ELEMENT code (#PCDATA)>
<!ATTLIST code value CDATA #REQUIRED>
<!ATTLIST code goto CDATA #REQUIRED>

=== austinejei/xmltoussd/xmltoussd.app/form_list_with_script.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ussd SYSTEM "xml2ussd.dtd">
<ussd>

  <screen id="main" main="true">

 <form bindto="user" onsubmit="ussd:nav:finish">
      <title>Welcome to my USSD application</title>
      <input type="text" display="Enter your name" 
             id="name" required="true"/>

      <input type="list" listid="networkList" id="Network" display="Select Network" required="true"/>


      <!--repeater example    -->
      <list id="networkList" repeater="ussd:script:networkListScript">
        
      </list>
      
    </form>
  </screen>

  <screen id="finish">
    <text bindfrom="user">
      Your name is {user.name}; you selected {user.Network}.
    </text>
  </screen>

  <script id="networkListScript" type="csharp">
  
    var networkListData = new[]
    {
    new {selector="1",value="62001",text="MTN"},
    new {selector="2",value="62002",text="Airtel"},
    };

    
    return new ScriptOutput{
        Response=networkListData
    };

  </script>

</ussd>

=== austinejei/xmltoussd/xmltoussd.app/menu_form_list_with_script.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ussd SYSTEM "xml2ussd.dtd">
<ussd>
	<screen id="mainscreen" main="true">
   
		<menu  bindaction="ussd:script:mainScreenScript" bindfrom="user" >
			<title>
        MAIN MENU\r\n Hello {user.AccountId}, welcome to CashBagg
      </title>
      
			<option value="1"  onselect="ussd:nav:busy4gScreen">1. Buy BUSY 4G Bundle ({user.AccountStatus})</option>
	
			<option value="2"  onselect="ussd:nav:exitScreen">2. Exit</option>

		</menu>
	</screen>


  <screen id="busy4gScreen">
    <form bindto="busyAccount" onsubmit="ussd:nav:confirmScreen">
      <title>BUSY 4G Bundle</title>
      <input type="number" display="Enter your account number"
             id="account" required="true"/>
     <input type="list" listid="bundleList" id="bundle" display="Select Bundle" required="true"/>

   <list id="bundleList" repeater="ussd:script:queryBusy4gScript">
        
      </list>
    </form>
  </screen>
  
  <screen id="confirmScreen">
   
		<menu  bindaction="ussd:script:confirmScreenScript" bindfrom="busyAccountFormatted" >
			<title>
        CONFIRM\r\n Are you sure you want to buy {busyAccountFormatted.SelectedBundle.ShortName} at GHS {busyAccountFormatted.SelectedBundle.Value} for {busyAccountFormatted.Firstname} {busyAccountFormatted.Lastname} ({busyAccountFormatted.Msisdn})?
      </title>
      
			<option value="1"  onselect="ussd:script:buyBusyBundleScript">1. YES - {busyAccountFormatted.SelectedBundle.ShortName}</option>
	
			<option value="2"  onselect="ussd:nav:mainscreen">2. NO</option>

		</menu>
	</screen>
      
   <screen id="busyPaymentCompleted" >
    <text bindfrom="busyPurchaseResponse">
      Completed. Transaction ID is {busyPurchaseResponse.Id}
    </text>
  </screen>

  <screen id="serviceDownScreen" >
    <text>
      Service down. Please try again later.
    </text>
  </screen>
  
  
  <screen id="exitScreen" >
    <text bindfrom="user">
      Goodbye, {user.AccountId}
    </text>
  </screen>

  <script id="buyBusyBundleScript" type="csharp" bindto="busyPurchaseResponse" bindfrom="busyAccountFormatted">
    string responseString = string.Empty;

    try{
    using(var client = new HttpClient()){
    client.DefaultRequestHeaders.Clear();
    client.DefaultRequestHeaders.Add("Authorization","Basic ZHlreXVuenM6a29kd3l6aGw=");

    HttpContent content = new StringContent(JsonConvert.SerializeObject(new{
    account = busyAccountFormatted.Msisdn,
    token = "c81f1a54-2431-48d6-8772-ee9aa300d063",
    amount = busyAccountFormatted.SelectedBundle.Value,
    bundle = busyAccountFormatted.SelectedBundle.Bundle
    }),System.Text.Encoding.UTF8,"application/json");

    var resp = client.PostAsync(new Uri("http://api.smsgh.com/usp/test/busy"),content).Result;

    if(!resp.IsSuccessStatusCode){
    return new ScriptOutput{
    Response = null,
    NextScreen = "serviceDownScreen"
    };
    }

    responseString = resp.Content.ReadAsStringAsync().Result;

    }
    }
    catch(Exception e){
    return new ScriptOutput{
    Response = e.Message,
    NextScreen = "serviceDownScreen"
    };
    }

    return new ScriptOutput{
    NextScreen = "busyPaymentCompleted",
    Response=JObject.Parse(responseString)
    };

  </script>

  <script id="confirmScreenScript" type="csharp" bindto="busyAccountFormatted" bindfrom="busyAccount">

    var selectedBundleDetail = JObject.Parse(busyAccount.bundle);

    return new ScriptOutput{
    
    Response=selectedBundleDetail
    };
  </script>
  
  <script id="mainScreenScript" type="csharp" bindto="user">

    string responseString = string.Empty;

    try{
    using(var client = new HttpClient()){
    client.DefaultRequestHeaders.Clear();
    client.DefaultRequestHeaders.Add("Authorization","Basic ZHlreXVuenM6a29kd3l6aGw=");
    var resp = client.GetAsync(new Uri("http://api.smsgh.com/v3/account/profile")).Result;

    if(!resp.IsSuccessStatusCode){
    return new ScriptOutput{
    Response = null,
    NextScreen = "serviceDownScreen"
    };
    }

    responseString = resp.Content.ReadAsStringAsync().Result;

    }
    }
    catch(Exception e){
    return new ScriptOutput{
    Response = null,
    NextScreen = "serviceDownScreen"
    };
    }



    return new ScriptOutput{
    Response=JObject.Parse(responseString)
    };
  </script>

  <script id="queryBusy4gScript" type="csharp" bindto="busyQueryOutput" bindfrom="busyAccount">

    public class BusyQueryDetail{
    public BusyQueryDetail(){

    Bundles = new List&lt;BusyBundle&gt;();

        }
        public string Msisdn {get;set;}
        public string Firstname {get;set;}
        public string Lastname {get;set;}
        public List&lt;BusyBundle&gt; Bundles {get;set;}
          }

    
        public class BusyBundle{
        public string Value{get;set;}
        public string ShortName{get;set;}
        public string Name{get;set;}
        public string Bundle{get;set;}
        }
        
        public class LussdListItem{
        public string value{get;set;}
        public string selector{get;set;}
        public string text{get;set;}
        
        }

        string responseString = string.Empty;

        try{
        using(var client = new HttpClient()){
        client.DefaultRequestHeaders.Clear();
        client.DefaultRequestHeaders.Add("Authorization","Basic ZHlreXVuenM6a29kd3l6aGw=");
        var resp = client.GetAsync(new Uri("http://api.smsgh.com/usp/test/busy?account=" + busyAccount.account)).Result;

        if(!resp.IsSuccessStatusCode){
        return new ScriptOutput{
        Response = null,
        NextScreen = "serviceDownScreen"
        };
        }

        responseString = resp.Content.ReadAsStringAsync().Result;

        }
        }
        catch(Exception e){
        return new ScriptOutput{
        Response = e.Message,
        NextScreen = "serviceDownScreen"
        };
        }

      var accountDetails = JsonConvert.DeserializeObject&lt;BusyQueryDetail&gt;(responseString);
      
      int i=0;
      
      var lussdList = new List&lt;LussdListItem&gt;();
      
      foreach(var c in accountDetails.Bundles){
        i++;
        lussdList.Add(new LussdListItem{
             selector = (i).ToString(),
              text = c.ShortName,
              //value = c.Bundle + ":" + c.Value + ":" + c.ShortName
              value = JsonConvert.SerializeObject(new{accountDetails.Firstname,accountDetails.Lastname,accountDetails.Msisdn, SelectedBundle=c})
            });
       
      }
      
          
             
    return new ScriptOutput{
    Response= lussdList
    };
  </script>


</ussd>

=== austinejei/xmltoussd/xmltoussd.app/simpleussd2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ussd SYSTEM "xml2ussd.dtd">
<ussd>

  <screen id="main">
    <form bindto="user" onsubmit="ussd:nav:finish">
      <title>Welcome to my USSD application</title>
      <input type="text" display="Enter your name" 
             id="name" required="true"/>

      <input type="list" listid="networkList" id="Network" display="Select Network" required="true"/>

      <list id="networkList">
        <choice value="62001" selector="1">MTN</choice>
        <choice value="62002" selector="2">Airtel</choice>
        <choice value="62003" selector="3">Glo</choice>
        <choice value="62004" selector="4">Vodafone</choice>
      </list>
    </form>
  </screen>

  <screen id="finish">
    <text bindfrom="user">
      Your name is {user.name}; you selected {user.Network}.
    </text>
  </screen>

</ussd>

=== austinejei/xmltoussd/xmltoussd.app/form_with_script.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ussd SYSTEM "xml2ussd.dtd">
<ussd>

  <screen id="mainScreen" main="true" >
    <form bindto="user" onsubmit="ussd:script:finishScript">
      <title>Welcome to my USSD application</title>
      <input type="text" display="Enter your name here:" id="name" required="true"/>
      
    </form>
  </screen>

  <screen id="finishScreen">
    <text bindfrom="user2">
      Your name is {user2.name}.
    </text>
  </screen>
  
  <script id="finishScript" bindfrom="user" bindto="user2" type="csharp">


    var userResponse = user.name + ". And today is "+ DateTime.Now.ToString("F");
    
    return new ScriptOutput{
         Response=new{
              name = userResponse
         },
         NextScreen = "finishScreen"
    };

  </script>

</ussd>

=== austinejei/xmltoussd/xmltoussd.app/simple_menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ussd SYSTEM "xml2ussd.dtd">
<ussd>
	<screen id="mainscreen" main="true">
   
		<menu>
			<title>
					 MAIN MENU\r\nWelcome to CashBagg	
			</title>
      
			<option value="1"  onselect="ussd:nav:accountinfoscreen">1. Account Info</option>
	
			<option value="2"  onselect="ussd:nav:exitapp">2. Exit</option>

		</menu>
	</screen>


  <screen id="accountinfoscreen">
    <menu>
      <title>
        ACCOUNT INFO\r\nYou have GHS 34660.00 in your account
      </title>
      <option value="0" onselect="ussd:nav:mainscreen">0.Back</option>
    </menu>
  </screen>
  
  <screen id="exitapp" >
    <text>
      Goodbye
    </text>
  </screen>
	
	


</ussd>

=== austinejei/xmltoussd/xmltoussd.app/menu_with_script.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ussd SYSTEM "xml2ussd.dtd">
<ussd>
	<screen id="mainscreen" main="true">
   
		<menu  bindaction="ussd:script:firstTimeScript" bindfrom="user" >
			<title>
					 MAIN MENU\r\n Hello {user.name}, welcome to CashBagg	
			</title>
      
			<option value="1"  onselect="ussd:nav:accountinfoscreen">1. Account Info</option>
	
			<option value="2"  onselect="ussd:nav:exitapp">2. Exit</option>

		</menu>
	</screen>


  <screen id="accountinfoscreen">
    <menu bindfrom="user">
      <title>
        ACCOUNT INFO\r\nYou have GHS {user.accountbalance} in your account
      </title>
      <option value="0" onselect="ussd:nav:mainscreen">0.Back</option>
    </menu>
  </screen>
  
  <screen id="exitapp" >
    <text bindfrom="user">
      Goodbye, {user.name}
    </text>
  </screen>

  <script id="firstTimeScript" type="csharp" bindto="user">

    return new ScriptOutput{
        Response=new{
          name = "Gyawu",
          accountbalance = 52068
        }
    };
  </script>
	


</ussd>
